### PR TITLE
docs: Example projects

### PR DESCRIPTION
**Pull request by NeoLight1010**
This PR adds minimal example projects for Jest and Mocha, solving issue #63 .

Some details:
- The examples resolve the `assertive-ts` depdendency by using [Yarn workspaces](https://yarnpkg.com/features/workspaces). I based this on how examples are set up in [Jest's source code](https://github.com/facebook/jest). This required adding a `workspaces` field to the top level `package.json` file. Please tell me if I should use another approach.
- I followed the instructions from the documentation as they are. That's why there are two `tsconfig.json` files with a lot of commented-out fields (generated by `npx tsc -init`).

### CODE REVIEW

**Comment by JoseLion** [comment]
@NeoLight1010, thanks a lot for your contribution. We recently changed the CI configuration to allow the build workflow to trigger on forked PRs too. Can you please update your branch with the latest changes from `main`? Thanks 🙂

**Comment by NeoLight1010** [comment]
Thank you! I updated my branch, but it seems the workflow still needs approval to be run

**Comment by NeoLight1010** [comment]
The workflow is failing because `yarn install` would modify the lockfile, due to the dependencies of the example projects. To solve the issue, I can commit the modified lockfile or I can stop using Yarn workspaces altogether. Please tell me your opinion so I can solve the issue @JoseLion :smile:

**Comment by JoseLion** [comment]
@NeoLight1010 yes, I think using Yarn workspaces is a good approach for this. You can commit the modified lock file to solve the workflow issue. A couple of extra things:
- Can you please change the workspace code to use 2-space indentation to keep consistency with the project?
- We'll also need to exclude the workspace `node_modules` from the linter execution or we'll get a lot of lint errors on CI. You can do this by adding a pattern to the `linterOptions.exclude` property on the `tslint.json` file. Maybe something like the following:

```json
"linterOptions": {
  "exclude": [
    "node_modules/**/*",
    "examples/*/node_modules/**/*"
  ]
}
```

And thanks again for your contribution! 🙂 🎉

**Comment by NeoLight1010** [comment]
Sorry, I didn't notice the linting rules of the project. I added the exception to the linter's rules, formatted the examples' code and fixed the linter's warnings. I also added a peer dependency missing in the Mocha example that was causing a warning when running `yarn install`.

**Review by JoseLion — APPROVED** [review]
Looks great! I think this is perfect for getting started with the examples. Thanks again for your contribution! 🚀 🎉

**Comment by NeoLight1010** [comment]
You're welcome! And thank you for this amazing library! :tada:

**Comment by JoseLion** [comment]
@all-contributors please add @NeoLight1010 for doc

**Pull request merged**
